# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(default='anony.jpg', upload_to=sales.models.update_location),
        ),
    ]
